# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"]\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\x12\"\n\x1aold_leader_lease_remaining\x18\x03 \x01(\x02\"\xd4\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\x0f\n\x07\x65ntries\x18\x05 \x03(\t\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\x12\x16\n\x0elease_interval\x18\x07 \x01(\x05\x12\x1e\n\x16remaining_leader_lease\x18\x08 \x01(\t\x12\x0c\n\x04\x66lag\x18\t \x01(\x08\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"&\n\x0bSetResponse\x12\x17\n\x0fresponseMessage\x18\x01 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xcf\x01\n\x0fRaftNodeService\x12\x38\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponse\x12>\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x16.AppendEntriesResponse\x12 \n\x03SET\x12\x0b.SetRequest\x1a\x0c.SetResponse\x12 \n\x03GET\x12\x0b.GetRequest\x1a\x0c.GetResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTVOTEREQUEST']._serialized_start=14
  _globals['_REQUESTVOTEREQUEST']._serialized_end=117
  _globals['_REQUESTVOTERESPONSE']._serialized_start=119
  _globals['_REQUESTVOTERESPONSE']._serialized_end=212
  _globals['_APPENDENTRIESREQUEST']._serialized_start=215
  _globals['_APPENDENTRIESREQUEST']._serialized_end=427
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=429
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=483
  _globals['_SETREQUEST']._serialized_start=485
  _globals['_SETREQUEST']._serialized_end=525
  _globals['_SETRESPONSE']._serialized_start=527
  _globals['_SETRESPONSE']._serialized_end=565
  _globals['_GETREQUEST']._serialized_start=567
  _globals['_GETREQUEST']._serialized_end=592
  _globals['_GETRESPONSE']._serialized_start=594
  _globals['_GETRESPONSE']._serialized_end=637
  _globals['_RAFTNODESERVICE']._serialized_start=640
  _globals['_RAFTNODESERVICE']._serialized_end=847
# @@protoc_insertion_point(module_scope)
