# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import KMeans_pb2 as KMeans__pb2


class MapperStub(object):
    """Reduce Mapper files ko RPC call se read karega <---- YET TO BE IMPLEMENTED IN CODE ---->
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MapTask = channel.unary_unary(
                '/Mapper/MapTask',
                request_serializer=KMeans__pb2.MapRequest.SerializeToString,
                response_deserializer=KMeans__pb2.MapResponse.FromString,
                )
        self.ServeData = channel.unary_unary(
                '/Mapper/ServeData',
                request_serializer=KMeans__pb2.ReadRequest.SerializeToString,
                response_deserializer=KMeans__pb2.ReadResponse.FromString,
                )


class MapperServicer(object):
    """Reduce Mapper files ko RPC call se read karega <---- YET TO BE IMPLEMENTED IN CODE ---->
    """

    def MapTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServeData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MapTask': grpc.unary_unary_rpc_method_handler(
                    servicer.MapTask,
                    request_deserializer=KMeans__pb2.MapRequest.FromString,
                    response_serializer=KMeans__pb2.MapResponse.SerializeToString,
            ),
            'ServeData': grpc.unary_unary_rpc_method_handler(
                    servicer.ServeData,
                    request_deserializer=KMeans__pb2.ReadRequest.FromString,
                    response_serializer=KMeans__pb2.ReadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Mapper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mapper(object):
    """Reduce Mapper files ko RPC call se read karega <---- YET TO BE IMPLEMENTED IN CODE ---->
    """

    @staticmethod
    def MapTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Mapper/MapTask',
            KMeans__pb2.MapRequest.SerializeToString,
            KMeans__pb2.MapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServeData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Mapper/ServeData',
            KMeans__pb2.ReadRequest.SerializeToString,
            KMeans__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ReducerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReduceTask = channel.unary_unary(
                '/Reducer/ReduceTask',
                request_serializer=KMeans__pb2.ReduceRequest.SerializeToString,
                response_deserializer=KMeans__pb2.ReduceResponse.FromString,
                )


class ReducerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReduceTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReducerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReduceTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ReduceTask,
                    request_deserializer=KMeans__pb2.ReduceRequest.FromString,
                    response_serializer=KMeans__pb2.ReduceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Reducer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Reducer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReduceTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reducer/ReduceTask',
            KMeans__pb2.ReduceRequest.SerializeToString,
            KMeans__pb2.ReduceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
