# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notificationService.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19notificationService.proto\"\xbc\x01\n\x13NotifyClientRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0bproductName\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x15\n\rsellerAddress\x18\x06 \x01(\t\x12\x14\n\x0cpricePerUnit\x18\x07 \x01(\x01\x12\x13\n\x06rating\x18\x08 \x01(\x01H\x00\x88\x01\x01\x42\t\n\x07_rating\"g\n\x14NotifyClientResponse\x12,\n\x06status\x18\x01 \x01(\x0e\x32\x1c.NotifyClientResponse.Status\"!\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32R\n\x13NotificationService\x12;\n\x0cNotifyClient\x12\x14.NotifyClientRequest\x1a\x15.NotifyClientResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notificationService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFYCLIENTREQUEST']._serialized_start=30
  _globals['_NOTIFYCLIENTREQUEST']._serialized_end=218
  _globals['_NOTIFYCLIENTRESPONSE']._serialized_start=220
  _globals['_NOTIFYCLIENTRESPONSE']._serialized_end=323
  _globals['_NOTIFYCLIENTRESPONSE_STATUS']._serialized_start=290
  _globals['_NOTIFYCLIENTRESPONSE_STATUS']._serialized_end=323
  _globals['_NOTIFICATIONSERVICE']._serialized_start=325
  _globals['_NOTIFICATIONSERVICE']._serialized_end=407
# @@protoc_insertion_point(module_scope)
